name: Build

on:
  push:
    branches: [ master ]
    tags-ignore: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure git line endings
      run: git config --global core.autocrlf true

    - name: Setup .NET SDK
      run: .\init.ps1 -NoRestore
      shell: pwsh

    - name: Restore NuGet packages
      run: dotnet restore StyleCopAnalyzers.slnx

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild StyleCopAnalyzers.slnx /p:Configuration=${{ matrix.configuration }} /v:minimal -warnAsError -warnNotAsError:NU1901,NU1902,NU1903,NU1904

    - name: Run tests
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build

    - name: Upload NuGet packages
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: NuGet-Packages
        path: StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/bin/Release/*.nupkg

  docs:
    name: ðŸ“ƒ Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: âš™ Install prerequisites
      run: ./init.ps1
    - name: ðŸ“š Verify docfx build
      run: dotnet docfx docfx/docfx.json --warningsAsErrors --disableGitFeatures
